# Site settings
title: Gang's Blog
email: nickyhg@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  A C++ software engineer, interested in computer graphics.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: nicholashu
github_username:  windfoxcn

# Build settings
markdown: kramdown
